name: GUT

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Godot 4.4.1
        uses: chickensoft-games/setup-godot@v1
        with:
          version: "4.4.1"
          use-dotnet: false
          export-templates: false

      - name: Import Godot Assets
        run: |
          godot --headless --import

      - name: Run GUT Tests
        run: |
          godot --headless --path . \
            --script res://addons/gut/gut_cmdln.gd \
            -gdir=res://test \
            -ginclude_subdirs \
            -gexit
